/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.formula1;

public class App {

    //main class to run the game.

    public static void main(String[] args) {

        SimpleTrack track = new SimpleTrack();
        track.createTrack();

        BotCar botCar1 = new BotCar("bot1", track);
        BotCar botCar2 = new BotCar("bot2", track);
        HumanCar humanCar1 = new HumanCar("racer1", track);

        GameSetup setup = new GameSetup(track);
        setup.addBot(botCar1);
        setup.addBot(botCar2);
        setup.addPlayer(humanCar1);
        setup.placePlayers();
        track.displayTrack();

        GamePlay game = new GamePlay(setup, track);
        game.startGame();
    }
}
