/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.formula1;

public class App {

    //main class to run the game.

    public static void main(String[] args) {

        SimpleTrack track = new SimpleTrack();
        track.loadTrack();
        track.createTrack();

        BotMovementStrategy bot1Strategy = new BotMovementStrategy();
        BotMovementStrategy bot2Strategy = new BotMovementStrategy();
        HumanMovementStrategy humanStrategy = new HumanMovementStrategy();

        GameSetup setup = new GameSetup(track);
        setup.loadPlayers();
        for (iRacer player : setup.getPlayers()){
            setup.placePlayer(player);
        }
        track.displayTrack();

        GamePlay game = new GamePlay(setup, track);
        game.startGame();
    }
}
