/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.formula1;

public class App {

    //main class to run the game

    public static void main(String[] args) {
        GamePlay game = new GamePlay();

        SimpleTrack track = new SimpleTrack();
        track.createTrack();

        BotCar botCar1 = new BotCar("bot1");
        BotCar botCar2 = new BotCar("bot2");
        HumanCar humanCar1 = new HumanCar("racer1");
        game.addBot(botCar1);
        game.addBot(botCar2);
        game.addPlayer(humanCar1);

        track.placePlayers(game.getPlayersPositions());
        track.displayTrack();

        game.startGame(botCar1, botCar2, humanCar1, track);
    }
}
